# Generated by Django 3.2.7 on 2021-09-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=90)),
                ('price', models.CharField(max_length=90)),
                ('year', models.CharField(max_length=90)),
                ('mileage', models.CharField(max_length=90)),
            ],
        ),
    ]
